version: '3.7'

services:
  nuxt:
    image: node:20
    volumes:
      - ./ia:/home/node/app
    working_dir: /home/node/app
    ports:
      - "3000:3000"
    depends_on:
      - laravel
    command: bash -c "npm install && npm run dev"

  laravel:
    build:
      context: ./back/api-laravel
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./back/api-laravel:/var/www/html
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: fithub
      DB_USERNAME: root
      DB_PASSWORD: 

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - laravel
